### ISSUE TITLE
Failing install tests on rakudo-moar-2021.10-100-g505ffbfa1

### ISSUE THREAD

**Issue by japhb** [jonathanstowe/Crypt-SodiumPasswordHash#2]
Error seen:

```
===> Testing: Crypt::SodiumPasswordHash:ver<0.0.2>:auth<github:jonathanstowe>:api<1.0>
===SORRY!===
Missing serialize REPR function for REPR VMException (BOOTException)

  in block <unit> at t/030-hash.t line 28

===> Testing [FAIL]: Crypt::SodiumPasswordHash:ver<0.0.2>:auth<github:jonathanstowe>:api<1.0>
```

**Comment by jonathanstowe** [comment]
Looking, but it's been broken by the new dispatch nativecall,  see bisect in https://github.com/rakudo/rakudo/issues/4643

**Comment by jonathanstowe** [comment]
Fixed with https://github.com/jonathanstowe/Crypt-SodiumPasswordHash/tree/v0.0.3 - winging its way to CPAN at this moment.

**Comment by japhb** [comment]
Not fixed, unfortunately; the changes for `v0.0.3` missed a `LibraryCheck` reference in the tests:

https://github.com/jonathanstowe/Crypt-SodiumPasswordHash/blob/master/t/030-hash.t#L6

**Comment by jonathanstowe** [comment]
The tests pass,  the problem was nothing to do with it being used in the tests.  The problem was due to it being used in place that was precompiled.

**Comment by japhb** [comment]
Ah, I think I was unclear: `LibraryCheck` is still being used in the tests, but is no longer in `META6` so a *fresh from scratch* Rakudo/zef rebuild will not install `LibraryCheck`, and zef will fail tests in this module because Rakudo can't find `LibraryCheck`.  (When I do my rebuilds, I wipe all zef storage and start from scratch in a new isolated tree, just to catch this kind of thing.)

I think the reason the tests passed for you is that you still had `LibraryCheck` installed.

**Comment by jonathanstowe** [comment]
Oh it was probably me being thick, it wouldn't be the first time :rofl: 

The `LibraryCheck` is just in the test depends now https://github.com/jonathanstowe/Crypt-SodiumPasswordHash/blob/master/META6.json#L23 - *but* looking at the [CI Job](https://github.com/jonathanstowe/Crypt-SodiumPasswordHash/runs/4238057198) it doesn't appear to install it (nor `NativeLibs` ) *and still passes*.

I'll take a look in a pristine docker container later.

**Comment by jonathanstowe** [comment]
Ok, I'd cocked up the `depends` such that it wasn't installing the test dependencies.

Just re-testing, then I'll re-release.

**Comment by jonathanstowe** [comment]
the v0.0.4 should be good. 

Will have a look at `Test::META` to see if it can catch what I did.

**Comment by japhb** [comment]
Yup, latest version worked for me.  :-)
